// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "happyness joy":return img`
..........c..............cdddd
.........c6cc..cccc......cddcc
..........c66cc6666cc...cdddc.
......c..c66666666667c..cddc..
.cccccdc.c67666666766cccdddc..
cddddddc.c667666666766ccddc...
cddddddc..c667777766676dddc...
.cccccddc..c67dd7777767ddc....
......cddcc66cd961dd977ddc....
.......cddc666d86fdd6fbcc.....
........cddc6d6ddddddddc......
.........cdd6bddddddddbc......
..........cddcddbeebddac......
...........cbcbddddddac.......
...........ccaaaabbbaac.......
............ca5aaabaa5c.......
.............caaaaaaaac.......
.............caa7aa55c........
..............ca55555c........
..............ca55575c........
..............ca55555c........
..............caa5555c........
...............caaaaac........
..............ca55555c........
.............caaaaaacc........
.............ca555555c........
............ca5555555c........
...........caaaaa5555c........
..........caa55555555c........
.........caa555a555555c.......
.........ca55aaa555555c.......
........ca555aa5555a755c......
.......caa55aa57555a555c......
......caa55aa555555a555c......
......ca55aa555a555a555ac.....
.......caaaaaaaaaaaaaaaac.....
........ccbbbbcccbbbcccc......
.........cdddc..cdddc.........
........cdddc...cdddc.........
.......cdddc....cdddc.........
......cddddc....cdddc.........
.....cddddc.....cdddc.........
.....cdddc.......cddc.........
....cdddc........cddc.........
....cddc.........cddc.........
...cdddc..........cddc........
...cddcc..........cdddc.......
...cddddc..........ccddc......
....cccc.............cc.......
..............................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
